package com.vtoptunov.passwordgenerator.domain.usecase.share

import android.content.Context
import android.content.Intent
import android.graphics.Bitmap
import com.vtoptunov.passwordgenerator.domain.model.Password
import com.vtoptunov.passwordgenerator.domain.usecase.transfer.ExportPasswordsUseCase
import dagger.hilt.android.qualifiers.ApplicationContext
import kotlinx.serialization.encodeToString
import kotlinx.serialization.json.Json
import java.security.SecureRandom
import java.util.Base64
import javax.crypto.Cipher
import javax.crypto.SecretKeyFactory
import javax.crypto.spec.IvParameterSpec
import javax.crypto.spec.PBEKeySpec
import javax.crypto.spec.SecretKeySpec
import javax.inject.Inject
import javax.inject.Singleton

/**
 * Secure Password Sharing
 * 
 * Features:
 * - Share via Android Share Sheet
 * - QR Code for quick scanning
 * - Optional password protection
 * - Time-limited sharing (metadata only)
 */
@Singleton
class SharePasswordUseCase @Inject constructor(
    @ApplicationContext private val context: Context,
    private val exportPasswordsUseCase: ExportPasswordsUseCase
) {
    
    /**
     * Share password as text (via Share Sheet)
     */
    fun shareAsText(password: Password, includeMetadata: Boolean = false): Intent {
        val text = if (includeMetadata) {
            buildString {
                appendLine("🔐 CyberSafe Password")
                appendLine()
                appendLine("Password: ${password.password}")
                if (password.note != null) {
                    appendLine()
                    appendLine("Note: ${password.note}")
                }
                appendLine()
                appendLine("Category: ${password.category.displayName}")
                appendLine("Created: ${java.text.SimpleDateFormat("yyyy-MM-dd HH:mm", java.util.Locale.US).format(java.util.Date(password.createdAt))}")
                appendLine()
                appendLine("Generated by CyberSafe Password Generator")
            }
        } else {
            password.password
        }
        
        return Intent.createChooser(
            Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_TEXT, text)
                type = "text/plain"
            },
            "Share Password"
        )
    }
    
    /**
     * Share password as QR Code
     */
    suspend fun shareAsQRCode(password: Password): Bitmap? {
        // Create minimal export with single password
        val passwordExport = exportPasswordsUseCase.invoke(listOf(password))
        
        // Generate QR code
        return exportPasswordsUseCase.generateQRCode(passwordExport)
    }
    
    /**
     * Share password with encryption (password-protected)
     * Returns encrypted password that can be decrypted with a passphrase
     */
    fun shareEncrypted(password: Password, passphrase: String): ShareResult {
        try {
            // Generate salt for key derivation
            val salt = ByteArray(16)
            SecureRandom().nextBytes(salt)
            
            // Derive key from passphrase
            val keySpec = PBEKeySpec(passphrase.toCharArray(), salt, 10000, 256)
            val secretKeyFactory = SecretKeyFactory.getInstance("PBKDF2WithHmacSHA256")
            val secretKey = secretKeyFactory.generateSecret(keySpec)
            val key = SecretKeySpec(secretKey.encoded, "AES")
            
            // Generate IV
            val iv = ByteArray(16)
            SecureRandom().nextBytes(iv)
            val ivSpec = IvParameterSpec(iv)
            
            // Encrypt password
            val cipher = Cipher.getInstance("AES/CBC/PKCS5Padding")
            cipher.init(Cipher.ENCRYPT_MODE, key, ivSpec)
            val encrypted = cipher.doFinal(password.password.toByteArray())
            
            // Encode everything to Base64
            val saltBase64 = Base64.getEncoder().encodeToString(salt)
            val ivBase64 = Base64.getEncoder().encodeToString(iv)
            val encryptedBase64 = Base64.getEncoder().encodeToString(encrypted)
            
            // Create shareable string
            val shareableText = buildString {
                appendLine("🔐 CyberSafe Encrypted Password")
                appendLine()
                appendLine("This password is encrypted with AES-256.")
                appendLine("Use CyberSafe app to decrypt.")
                appendLine()
                appendLine("--- BEGIN ENCRYPTED PASSWORD ---")
                appendLine("SALT:$saltBase64")
                appendLine("IV:$ivBase64")
                appendLine("DATA:$encryptedBase64")
                appendLine("--- END ENCRYPTED PASSWORD ---")
                appendLine()
                appendLine("Passphrase required for decryption.")
            }
            
            return ShareResult(
                success = true,
                data = shareableText,
                error = null
            )
        } catch (e: Exception) {
            return ShareResult(
                success = false,
                data = null,
                error = e.message
            )
        }
    }
    
    /**
     * Share multiple passwords at once
     */
    fun shareMultiple(passwords: List<Password>): Intent {
        val text = buildString {
            appendLine("🔐 CyberSafe Passwords (${passwords.size})")
            appendLine()
            passwords.forEachIndexed { index, password ->
                appendLine("${index + 1}. ${password.category.displayName}")
                appendLine("   Password: ${password.password}")
                if (password.note != null) {
                    appendLine("   Note: ${password.note}")
                }
                appendLine()
            }
            appendLine("Generated by CyberSafe Password Generator")
        }
        
        return Intent.createChooser(
            Intent().apply {
                action = Intent.ACTION_SEND
                putExtra(Intent.EXTRA_TEXT, text)
                type = "text/plain"
            },
            "Share ${passwords.size} Passwords"
        )
    }
}

data class ShareResult(
    val success: Boolean,
    val data: String?,
    val error: String?
)
